import "./input.css";
const materials=[
{id:"cement",i:"🧱",n:"Cement",b:"UltraTech",p:"OPC / PPC — select grade with engineer",u:"Concrete, mortar, plaster and masonry work.",q:1243,x:"bag",r:480,c:"Structure"},
{id:"sand",i:"🏖️",n:"Sand",b:"Local supplier",p:"Washed / approved sand",u:"Concrete, mortar and plaster.",q:2750,x:"cu ft",r:50,c:"Structure"},
{id:"aggregate",i:"🪨",n:"Aggregate / Gitti",b:"Local supplier",p:"Approved graded aggregate",u:"RCC and PCC concrete.",q:900,x:"cu ft",r:130,c:"Structure"},
{id:"steel",i:"🔩",n:"TMT Steel",b:"Tata Tiscon",p:"Grade as per structural design",u:"RCC reinforcement in columns, beams and slabs.",q:4800,x:"kg",r:60,c:"Structure"},
{id:"bricks",i:"🧱",n:"Bricks / Blocks",b:"Local approved supplier",p:"Brick / AAC block",u:"Internal and external walls.",q:27000,x:"piece",r:6,c:"Masonry"},
{id:"binding",i:"〰️",n:"Binding Wire",b:"Local approved supplier",p:"GI binding wire",u:"Tying reinforcement bars.",q:850,x:"kg",r:70,c:"Structure"},
{id:"stone",i:"⛰️",n:"Stone Dust",b:"Local supplier",p:"Approved stone dust",u:"Filling, bedding and selected construction work.",q:400,x:"cu ft",r:50,c:"Site"},
{id:"excavation",i:"🚜",n:"Excavation",b:"Local contractor",p:"Machine / manual excavation",u:"Foundation trenches and pits.",q:450,x:"cu yd",r:450,c:"Site"},
{id:"pcc",i:"🏗️",n:"PCC",b:"Site mix / RMC",p:"Mix as designed",u:"Clean and stable base below foundations.",q:90,x:"cu ft",r:120,c:"Foundation"},
{id:"rcc",i:"🏢",n:"RCC Work",b:"Site mix / RMC",p:"Structural mix as designed",u:"Slabs, beams, columns and structural elements.",q:6000,x:"sq ft",r:80,c:"Structure"},
{id:"masonry",i:"🧱",n:"Brick Masonry",b:"Local contractor",p:"Masonry labour + mortar",u:"Walls and partitions.",q:9500,x:"sq ft",r:60,c:"Masonry"},
{id:"plaster",i:"🪣",n:"Plaster",b:"Local contractor",p:"Internal + external plaster",u:"Smooth protective surface on walls and ceilings.",q:11000,x:"sq ft",r:20,c:"Finishes"},
{id:"waterproof",i:"💧",n:"Waterproofing",b:"Dr. Fixit",p:"System selected for area",u:"Roof, bathroom and wet-area protection.",q:900,x:"sq ft",r:50,c:"Finishes"},
{id:"flooring",i:"◼️",n:"Flooring",b:"Kajaria",p:"Tile / stone — select series",u:"Finished walking surface.",q:1200,x:"sq ft",r:112,c:"Finishes"},
{id:"doors",i:"🚪",n:"Doors & Windows",b:"Fenesta / local approved",p:"uPVC / aluminium / wood",u:"Access, ventilation, daylight and security.",q:1,x:"project",r:220000,c:"Finishes"},
{id:"electrical",i:"⚡",n:"Electrical",b:"Polycab + Havells",p:"Wires / switches / DB",u:"Wiring, sockets, lighting and distribution.",q:1,x:"project",r:165000,c:"Services"},
{id:"plumbing",i:"🚰",n:"Plumbing",b:"Astral / Supreme",p:"Pipes + fittings",u:"Fresh-water and wastewater systems.",q:1,x:"project",r:135000,c:"Services"},
{id:"sanitary",i:"🚿",n:"Sanitary Fittings",b:"Jaquar / CERA",p:"WC, basin, shower and fittings",u:"Bathroom fixtures.",q:1,x:"project",r:120000,c:"Finishes"},
{id:"painting",i:"🎨",n:"Painting",b:"Asian Paints / Berger",p:"Interior + exterior system",u:"Surface protection and final appearance.",q:1,x:"project",r:150000,c:"Finishes"},
{id:"kitchen",i:"🍳",n:"Kitchen",b:"Hettich / Häfele + local",p:"Cabinet, hardware, countertop",u:"Kitchen storage and work surfaces.",q:1,x:"project",r:180000,c:"Finishes"},
{id:"labour",i:"👷",n:"General Labour",b:"Local contractor",p:"Masonry + handling + general work",u:"Construction support and material handling.",q:1,x:"project",r:382500,c:"Labour"},
{id:"misc",i:"📦",n:"Miscellaneous",b:"Project allowance",p:"Transport, tools, wastage",u:"Small tools, transport, wastage and minor unforeseen expenses.",q:1,x:"project",r:100000,c:"Other"}
];
const brandMap={Cement:["UltraTech","ACC","Ambuja","Shree Cement"],"TMT Steel":["Tata Tiscon","JSW Neosteel","SAIL"],Waterproofing:["Dr. Fixit","Fosroc","Sika"],Electrical:["Polycab","Havells","Finolex"],Plumbing:["Astral","Supreme","Finolex"],"Sanitary Fittings":["Jaquar","CERA","Hindware"],Painting:["Asian Paints","Berger","Nerolac"],Flooring:["Kajaria","Somany","Johnson"]};
const s={theme:localStorage.getItem("ghar-theme")||"dark",area:1200,floors:1,finish:"Standard",rating:0};
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n); const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const factor=()=>Math.max(.65,s.area/1200)*(1+Math.max(0,s.floors-1)*.22)*(s.finish==="Premium"?1.22:s.finish==="Economy"?.86:1);
function render(){document.documentElement.dataset.theme=s.theme;const rows=materials.map(m=>{const q=m.x==="project"?m.q:+(m.q*factor()).toFixed(2);return {...m,q2:q,a:q*m.r}});const sub=rows.reduce((a,m)=>a+m.a,0),cont=sub*.05,total=sub+cont;document.querySelector("#app").innerHTML=`
<header class="nav"><div class="container nav-inner"><a class="brand" href="#"><span class="brand-mark">G</span>Ghar Setup PRO</a><nav class="nav-links"><a href="#planner">Planner</a><a href="#estimate">Estimate</a><a href="#feedback">Feedback</a></nav><button class="btn" id="theme">${s.theme==="dark"?"☀ Light":"☾ Dark"}</button></div></header>
<main><section class="hero"><div class="container hero-grid"><div><div class="eyebrow">HOME CONSTRUCTION OS</div><h1>Build your home with a plan you can actually understand.</h1><p>Plan construction stages, quantities, indicative rates and budget from foundation to final paint.</p></div><div class="hero-actions"><a class="btn" href="#estimate">View estimate →</a><a class="btn btn-primary" href="#planner">Start project</a></div></div></section>
<section class="section" id="planner"><div class="container"><div class="section-head"><div><h2>Project setup</h2><p>Change inputs and the indicative quantities update.</p></div><span class="badge">India • Indicative rates</span></div><div class="card card-pad"><div class="form-grid"><div class="field"><label>Built-up area (sq ft)</label><input id="area" type="number" min="100" value="${s.area}"></div><div class="field"><label>Number of floors</label><input id="floors" type="number" min="1" max="10" value="${s.floors}"></div><div class="field"><label>Finish level</label><select id="finish"><option ${s.finish==="Economy"?"selected":""}>Economy</option><option ${s.finish==="Standard"?"selected":""}>Standard</option><option ${s.finish==="Premium"?"selected":""}>Premium</option></select></div><div class="field"><label>City / state</label><input placeholder="e.g. Patna, Bihar"></div></div><p class="notice">Rates are demo/indicative. City, quality, supplier, specifications, taxes, soil and labour conditions can change final cost.</p></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><h2>Construction roadmap</h2><p>Stage-by-stage project view.</p></div></div><div class="stage-grid">${[["01","Plan","Survey, soil report, drawings, approvals & BOQ"],["02","Foundation","Layout, excavation, PCC, footing & plinth"],["03","Structure","Columns, beams, slabs, reinforcement & curing"],["04","Masonry","Walls, lintels, plaster and preparation"],["05","Services","Electrical, plumbing, drainage & waterproofing"],["06","Finishes","Flooring, doors, windows, paint and sanitary"],["07","Kitchen","Cabinets, countertop, hardware and appliances"],["08","Handover","Testing, snag list, cleaning and documents"]].map(x=>`<div class="stage"><div class="stage-number">${x[0]}</div><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join("")}</div></div></section>
<section class="section" id="estimate"><div class="container"><div class="section-head"><div><h2>Material & work estimate</h2><p>Item • brand/product • used for • quantity • unit • rate • amount</p></div><button class="btn" id="print">Print / Save PDF</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Item</th><th>Brand / product</th><th>Used for</th><th>Quantity</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows.map(m=>{const bs=[m.b,...(brandMap[m.n]||[])].filter((v,i,a)=>a.indexOf(v)===i);return `<tr><td><div class="item-name">${m.i} ${esc(m.n)}</div><span class="badge">${esc(m.c)}</span></td><td><select class="brand-select" data-id="${m.id}">${bs.map(b=>`<option ${b===m.b?"selected":""}>${esc(b)}</option>`).join("")}</select><div class="notice">${esc(m.p)}</div></td><td class="used-for">${esc(m.u)}</td><td>${m.q2}</td><td>${m.x}</td><td><input class="rate-input" data-id="${m.id}" type="number" min="0" value="${m.r}"><span class="notice">/ ${m.x}</span></td><td><strong>${money(m.a)}</strong></td></tr>`}).join("")}</tbody></table></div></div><div class="summary-grid" style="margin-top:12px"><div class="total"><small>Estimated construction subtotal</small><strong>${money(sub)}</strong><div class="notice">+ 5% planning contingency: ${money(cont)}</div></div><div class="total"><small>Planning estimate</small><strong>${money(total)}</strong><div class="notice">Not a contractor quotation or structural design.</div></div></div></div></section>
<section class="section" id="feedback"><div class="container"><div class="section-head"><div><h2>Help us improve Ghar Setup PRO</h2><p>Tell us what was useful or what is missing.</p></div></div><div class="feedback"><div class="card card-pad"><div class="field"><label>Your rating</label><div class="rating">${[1,2,3,4,5].map(n=>`<button data-rating="${n}" class="${s.rating===n?"active":""}">${n} ★</button>`).join("")}</div></div></div><div class="card card-pad"><div class="field"><label>Feedback</label><textarea id="feedbackText" rows="4" placeholder="What should we add next?"></textarea></div><button class="btn btn-primary" id="feedbackBtn" style="margin-top:12px">Send feedback</button><div id="status" class="notice" style="margin-top:8px"></div></div></div></div></section></main><footer class="footer"><div class="container">Ghar Setup PRO • Construction planning prototype • Indicative/demo rates only.</div></footer>`;bind()}
function bind(){document.querySelector("#theme").onclick=()=>{s.theme=s.theme==="dark"?"light":"dark";localStorage.setItem("ghar-theme",s.theme);render()};document.querySelector("#area").onchange=e=>{s.area=Number(e.target.value)||1200;render()};document.querySelector("#floors").onchange=e=>{s.floors=Math.max(1,Number(e.target.value)||1);render()};document.querySelector("#finish").onchange=e=>{s.finish=e.target.value;render()};document.querySelector("#print").onclick=()=>window.print();document.querySelectorAll(".rating button").forEach(b=>b.onclick=()=>{s.rating=+b.dataset.rating;render()});document.querySelector("#feedbackBtn").onclick=()=>{const t=document.querySelector("#feedbackText").value.trim(),st=document.querySelector("#status");st.textContent=!s.rating||!t?"Please select a rating and write a short message.":"Thanks — your feedback has been recorded for this prototype.";if(s.rating&&t)document.querySelector("#feedbackText").value=""};document.querySelectorAll(".rate-input").forEach(i=>i.onchange=e=>{const m=materials.find(x=>x.id===e.target.dataset.id);m.r=Math.max(0,+e.target.value||0);render()});document.querySelectorAll(".brand-select").forEach(i=>i.onchange=e=>{const m=materials.find(x=>x.id===e.target.dataset.id);m.b=e.target.value;render()})}render();
